# Generated by Django 5.1.1 on 2025-12-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(max_length=255, unique=True)),
                (
                    "cookies_data",
                    models.JSONField(default=dict, help_text="Stored session cookies"),
                ),
                ("passenger_name", models.CharField(max_length=255)),
                (
                    "passenger_value",
                    models.CharField(
                        help_text="legacyID from passenger select", max_length=255
                    ),
                ),
                (
                    "time_of_day_values",
                    models.JSONField(
                        default=dict, help_text="AM/MID/PM time span values"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_refresh", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BusData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_data",
                    models.JSONField(help_text="Raw response from bus tracking API"),
                ),
                (
                    "bus_location",
                    models.JSONField(
                        blank=True, help_text="Processed bus location data", null=True
                    ),
                ),
                ("request_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_data",
                        to="tablet.bussession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
