# Generated by Django 5.1.1 on 2025-12-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tablet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="busdata",
            name="request_headers",
            field=models.JSONField(
                default=dict, help_text="HTTP headers sent with the request"
            ),
        ),
        migrations.AddField(
            model_name="busdata",
            name="request_method",
            field=models.CharField(
                default="GET", help_text="HTTP method (GET, POST, etc.)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="busdata",
            name="request_parameters",
            field=models.JSONField(
                default=dict, help_text="Query params for GET, body params for POST"
            ),
        ),
        migrations.AddField(
            model_name="busdata",
            name="request_url",
            field=models.URLField(
                default="unknown",
                help_text="Full URL of the request made to bus tracking API",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="busdata",
            name="response_headers",
            field=models.JSONField(
                default=dict, help_text="HTTP headers received in the response"
            ),
        ),
        migrations.AddField(
            model_name="busdata",
            name="response_status_code",
            field=models.IntegerField(
                blank=True, help_text="HTTP status code", null=True
            ),
        ),
        migrations.AddField(
            model_name="busdata",
            name="response_text",
            field=models.TextField(
                default="unknown", help_text="Raw response text for debugging"
            ),
            preserve_default=False,
        ),
    ]
