# Generated by Django 5.1.1 on 2025-12-06 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tablet", "0002_busdata_request_headers_busdata_request_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busdata",
            name="response_data",
        ),
    ]
