# Generated by Django 5.1.1 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tablet", "0003_remove_busdata_response_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusDashboardSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Description of the skip period (e.g., 'Summer Break 2024')",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start date of the skip period (inclusive)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="End date of the skip period (inclusive)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this skip period is currently active",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Bus Dashboard Skip Period",
                "verbose_name_plural": "Bus Dashboard Skip Periods",
            },
        ),
    ]
