# Generated by Django 5.1.1 on 2024-09-09 02:00

import server.apps.storymagic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('sentences', models.JSONField(verbose_name='Sentences')),
                ('sentence_count', models.IntegerField(verbose_name='Sentence count')),
                ('topic', models.CharField(max_length=1024, verbose_name='Topic')),
                ('grade', models.CharField(choices=server.apps.storymagic.models.Grade.choices, max_length=24, verbose_name='Grade')),
            ],
        ),
    ]
