# Generated by Django 5.1.1 on 2024-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Content')),
                ('parsed_recipe', models.JSONField(verbose_name='Parsed Recipe')),
            ],
        ),
    ]
