# Generated by Django 5.1.1 on 2024-09-10 11:55

from django.db import migrations, models
from django.db.models.deletion import CASCADE

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    null=True,
                    on_delete=CASCADE,
                    related_name='recipes',
                    to='kitchenbuddy.user',
                )),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Content')),
                ('parsed_recipe', models.JSONField(verbose_name='Parsed Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(verbose_name='Items')),
                ('user', models.ForeignKey(
                    on_delete=CASCADE,
                    related_name='grocery_lists',
                    to='kitchenbuddy.user',
                )),
            ],
        ),
    ]
