# Generated by Django 5.1.1 on 2025-03-17 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='all_items_sorted',
            field=models.JSONField(default=list, verbose_name='All Items Sorted'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='kitchenbuddy.user'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'url')},
        ),
    ]
