# Generated by Django 5.1.3 on 2025-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kitchenbuddy",
            "0002_grocerylist_all_items_sorted_alter_grocerylist_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grocerylist",
            name="item_counts",
            field=models.JSONField(default=dict, verbose_name="Item Counts"),
        ),
    ]
